
  development:
    host: 127.0.0.1
    port: 3306
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: uitdraai
    pool: 20
    username: root
    password:
    socket: /var/run/mysqld/mysqld.sock
